import React, { useState, useRef, useEffect } from 'react';
import { UserMessage, AssistantMessage } from './ChatMessage';

interface ChatInteraction {
  id: number;
  query: string;
  response: string;
  timestamp: Date;
}

interface ChatComponentProps {
  chapterId?: number; // Optional: if chat is specific to a chapter
}

export const ChatComponent: React.FC<ChatComponentProps> = ({ chapterId }) => {
  const [inputValue, setInputValue] = useState<string>('');
  const [isLoading, setIsLoading] = useState<boolean>(false);
  const [chatHistory, setChatHistory] = useState<ChatInteraction[]>([]);
  const messagesEndRef = useRef<null | HTMLDivElement>(null);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!inputValue.trim() || isLoading) return;

    // Add user message to history
    const userMessage: ChatInteraction = {
      id: Date.now(),
      query: inputValue,
      response: '', // Will be filled when we get the response
      timestamp: new Date(),
    };

    setChatHistory((prev) => [...prev, userMessage]);
    setInputValue('');
    setIsLoading(true);

    try {
      // In a real implementation, this would call the backend API
      // This is a placeholder implementation
      await new Promise(resolve => setTimeout(resolve, 1000));
      
      // Mock response - in real implementation, this would come from API
      const mockResponse = `This is a simulated response to your question: "${inputValue}". In a real implementation, this would be generated by an AI model based on the textbook content.`;
      
      const assistantMessage: ChatInteraction = {
        id: Date.now() + 1,
        query: inputValue,
        response: mockResponse,
        timestamp: new Date(),
      };

      setChatHistory(prev => {
        const updatedHistory = [...prev];
        // Update the last message with the response
        updatedHistory[updatedHistory.length - 1] = assistantMessage;
        return updatedHistory;
      });
    } catch (error) {
      console.error('Error getting AI response:', error);
      // Add error message to chat
      const errorMessage: ChatInteraction = {
        id: Date.now() + 1,
        query: inputValue,
        response: 'Sorry, there was an error processing your request. Please try again later.',
        timestamp: new Date(),
      };
      setChatHistory(prev => [...prev, errorMessage]);
    } finally {
      setIsLoading(false);
    }
  };

  // Scroll to bottom when new messages are added
  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [chatHistory]);

  return (
    <div className="flex flex-col h-full border rounded-lg">
      <div className="p-4 border-b">
        <h3 className="text-lg font-semibold">AI Textbook Assistant</h3>
        <p className="text-sm text-gray-500">
          Ask questions about the textbook content, and I'll provide answers based on the material.
        </p>
      </div>
      
      <div className="flex-1 overflow-y-auto p-4 bg-gray-50 max-h-96">
        {chatHistory.length === 0 ? (
          <div className="text-center text-gray-500 py-8">
            <p>Ask your first question about the textbook!</p>
          </div>
        ) : (
          <div className="space-y-4">
            {chatHistory.map((interaction) => (
              <div key={interaction.id}>
                <UserMessage text={interaction.query} timestamp={interaction.timestamp} />
                {interaction.response && (
                  <AssistantMessage text={interaction.response} timestamp={interaction.timestamp} />
                )}
              </div>
            ))}
            {isLoading && (
              <div className="flex items-center space-x-2 text-blue-600">
                <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-blue-600"></div>
                <span>Thinking...</span>
              </div>
            )}
            <div ref={messagesEndRef} />
          </div>
        )}
      </div>
      
      <form onSubmit={handleSubmit} className="p-4 border-t bg-white">
        <div className="flex">
          <input
            type="text"
            value={inputValue}
            onChange={(e) => setInputValue(e.target.value)}
            placeholder="Ask a question about the textbook..."
            className="flex-1 border rounded-l-lg px-4 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
            disabled={isLoading}
          />
          <button
            type="submit"
            className="bg-blue-600 text-white px-4 py-2 rounded-r-lg hover:bg-blue-700 disabled:opacity-50"
            disabled={isLoading || !inputValue.trim()}
          >
            Send
          </button>
        </div>
        <p className="text-xs text-gray-500 mt-2">
          The AI assistant will respond based only on textbook content
        </p>
      </form>
    </div>
  );
};