import google.generativeai as genai
from typing import List
import os
import numpy as np

class EmbeddingService:
    def __init__(self):
        # Initialize the Google Gemini API key from environment
        api_key = os.getenv("GEMINI_API_KEY")
        if not api_key:
            raise ValueError("GEMINI_API_KEY environment variable is required")

        genai.configure(api_key=api_key)
        # Use the embedding model from Google Gemini
        self.model_name = "models/embedding-001"

    def generate_embedding(self, text: str) -> List[float]:
        """Generate embedding for a single text using Google Gemini"""
        try:
            result = genai.embed_content(
                model=self.model_name,
                content=text,
                task_type="retrieval_document",  # or "retrieval_query" depending on usage
                title="Textbook Content"  # Optional title for the content
            )
            # Convert to list of floats for JSON serialization
            return result['embedding']
        except Exception as e:
            print(f"Error generating embedding: {str(e)}")
            # Return a zero vector in case of error
            return [0.0] * 768  # Gemini embeddings typically have 768 dimensions

    def generate_embeddings(self, texts: List[str]) -> List[List[float]]:
        """Generate embeddings for multiple texts"""
        embeddings = []
        for text in texts:
            embedding = self.generate_embedding(text)
            embeddings.append(embedding)
        return embeddings

    def get_embedding_dimension(self) -> int:
        """Get the dimension of the embeddings generated by this model"""
        # Google's embedding-001 model typically has 768 dimensions
        return 768

# Create a singleton instance
embedding_service = EmbeddingService()