from dataclasses import dataclass
from typing import Dict, List, Optional
from datetime import datetime


@dataclass
class DocumentChunk:
    """
    Represents a segment of content extracted from a URL
    Based on the data model defined in data-model.md
    """
    id: str  # Unique identifier for the chunk (UUID or URL-based)
    content: str  # The cleaned text content (500-1000 token segment)
    source_url: str  # Original URL from which the content was extracted
    chunk_index: int  # Position of the chunk within the source document
    created_at: datetime = None  # Timestamp of when the chunk was created
    metadata: Dict = None  # Additional metadata like title, headings in the chunk

    def __post_init__(self):
        """Initialize optional fields if not provided"""
        if self.created_at is None:
            self.created_at = datetime.now()
        if self.metadata is None:
            self.metadata = {}

    def validate(self) -> bool:
        """Validate the DocumentChunk instance based on validation rules"""
        # Content length must be sufficient to represent meaningful information
        if not self.content or len(self.content.strip()) == 0:
            return False

        # Source URL must be a valid URL (basic check)
        if not self.source_url or not self.source_url.startswith(('http://', 'https://')):
            return False

        # Chunk index must be non-negative
        if self.chunk_index < 0:
            return False

        return True


@dataclass
class EmbeddingVector:
    """
    Numerical representation of text content generated by the Cohere model
    Based on the data model defined in data-model.md
    """
    chunk_id: str  # Reference to the Document Chunk
    vector: List[float]  # The embedding vector from Cohere model
    model: str  # Name of the model used (e.g., "multilingual-v3")
    created_at: datetime = None  # Timestamp of when the embedding was generated

    def __post_init__(self):
        """Initialize optional fields if not provided"""
        if self.created_at is None:
            self.created_at = datetime.now()

    def validate(self) -> bool:
        """Validate the EmbeddingVector instance based on validation rules"""
        # Vector must match the expected dimensionality of the Cohere model
        if not self.vector or len(self.vector) == 0:
            return False

        # Must reference a valid Document Chunk ID
        if not self.chunk_id:
            return False

        # Model name should be specified
        if not self.model:
            return False

        return True


@dataclass
class URLProcessingRecord:
    """
    Record of processing status for each URL
    Based on the data model defined in data-model.md
    """
    url: str  # The URL being processed
    status: str  # Processing status (e.g., "pending", "processing", "completed", "failed")
    processed_at: datetime = None  # Timestamp when processing was completed
    error_message: str = None  # Error message if processing failed
    chunk_count: int = 0  # Number of chunks created from the URL

    def __post_init__(self):
        """Initialize optional fields if not provided"""
        if self.processed_at is None:
            self.processed_at = datetime.now()
        if self.error_message is None:
            self.error_message = ""

    def validate(self) -> bool:
        """Validate the URLProcessingRecord instance based on validation rules"""
        # URL must be valid
        if not self.url or not self.url.startswith(('http://', 'https://')):
            return False

        # Status must be one of the defined values
        valid_statuses = ["pending", "processing", "completed", "failed"]
        if self.status not in valid_statuses:
            return False

        # Error message only if status is "failed"
        if self.status != "failed" and self.error_message:
            return False

        return True